-- EXPLORATORY DATA ANALYSIS NIEL BALAGTAS 4/20/2026

SELECT *
FROM cleaned_cafe_sales;

-- DATE RANGE
SELECT MIN(`Transaction Date`), MAX(`Transaction Date`)
FROM cleaned_cafe_sales;
-- THE WHOLE YEAR OF 2023

-- TOTAL REVENUE FOR THE YEAR OF 2023
-- I DECIDED TO INCLUDE DATES WITH NULL VALUES SINCE THE I AM LOOKING FOR THE TOTAL REVENUE
-- ALTHOUGH NOT RECORDED IT STILL HAS TO BE INCLUDED IN THE TOTAL REVENUE
WITH rolling_revenue AS
(
SELECT MONTH(`Transaction Date`) month_of_sales,
SUM(`Total Spent`) monthly_revenue
FROM cleaned_cafe_sales	
GROUP BY month_of_sales
)
SELECT *,
LAG(monthly_revenue) OVER(ORDER BY month_of_sales) AS previous_month_revenue,
monthly_revenue - LAG(monthly_revenue) OVER(ORDER BY month_of_sales) AS revenue_difference,
SUM(monthly_revenue) OVER(ORDER BY month_of_sales) AS rolling_total_final
FROM rolling_revenue;
-- $80 433 total_revenue
-- THE TABLE SHOWS THAT THE CAFE IS IN A STEADY STATE AS OF 2023
-- EACH MONTH DOES NOT GO UNDER $6000 BUT IT DOES NOT GO HIGHER THAT $7000
-- ALTHOUGH IT WOULD HAVE BEEN POSSIBLE TO STEP UP OR EXCEED $7000 IF THE NULLS ARE RECORDED PROPERLY


-- BEST SELLER OF THE CAFE
-- UNKNOWNS AND ERRORS ARE EXCLUDED TO ENSURE ITEM ACCURACY
SELECT Item, `Price Per Unit`, SUM(`Quantity`) AS total_sold, SUM(`Total Spent`) AS total_revenue
FROM cleaned_cafe_sales
WHERE Item NOT IN ('UNKNOWN', 'ERROR')
GROUP BY Item, `Price Per Unit`
ORDER BY total_sold DESC;
-- COFFEE IS THE HIGHEST SOLD ITEM WITH 3212 TOTAL SOLD WHILE COOKIE ONLY SOLD 2898 TOTAL UNITS
-- BUT THE ITEM THAT EARNED THE MOST IS THE SALAD WHICH ACCUMULATED $15 600 SALES


-- WHICH LOCATION OPTION SOLD THE MOST
SELECT Location, COUNT(`Transaction ID`) AS total_sold, SUM(`Total Spent`) AS total_revenue
FROM cleaned_cafe_sales
GROUP BY Location
ORDER BY total_sold DESC;
-- ALARMING SINCE UNRECORDED DATA HAS MORE THAN TOTAL SOLDS THEN THE TAKEAWAY OR THE IN-STORE OPTION
-- THIS SUGGESTS THAT THERE IS A PROBLEM/GLITCH IN THE POS OR THE EMPLOYEE BEHIND IT DOES NOT RECORD THE LOCATION OPTION
-- TAKEAWAY AND IN-STORE ARE HEAD TO HEAD MEANING THE CAFE IS BUILT TO SERVE BOTH IN-STORE AND TAKEAWAYS

-- END OF EDA